name: Build and deploy Node.js app to Azure Web App - zeusemployeeportal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BASE_PATH: "/"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
        env:
          BASE_PATH: ${{ env.BASE_PATH }}

      - name: Zip artifact for deployment
        run: zip -r release.zip .
        env:
          BASE_PATH: ${{ env.BASE_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    env:
      BASE_PATH: "/your-base-path"
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d release-dir
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zeusemployeeportal'
          slot-name: 'Production'
          package: ./release-dir
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC57EB58496B4D609D53EC3353E1ED97 }}
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
